# CMake generated Testfile for 
# Source directory: /home/anarkhede/tinkercliffs/FEMWorkingFoam
# Build directory: /home/anarkhede/tinkercliffs/FEMWorkingFoam
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(copyfiles "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/copy_files.pl" "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d" "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d")
set_tests_properties(copyfiles PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;776;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(buildInputs "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/buildInputs.py" "ALL")
set_tests_properties(buildInputs PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;777;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testStatics "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "-n" "statics")
set_tests_properties(testStatics PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;778;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testNLstatics "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "nlstatics")
set_tests_properties(testNLstatics PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;779;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testEigen "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "eigen")
set_tests_properties(testEigen PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;780;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testDynamics "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dynamics")
set_tests_properties(testDynamics PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;781;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testNLDynamics "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "nldynamics")
set_tests_properties(testNLDynamics PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;782;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testIMPE "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "impe")
set_tests_properties(testIMPE PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;783;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testFreqSweep "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "freqsweep")
set_tests_properties(testFreqSweep PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;784;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testTempStatics "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "tempstatics")
set_tests_properties(testTempStatics PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;785;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testTempNLStatics "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "tempnlstatics")
set_tests_properties(testTempNLStatics PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;786;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testTempDynamics "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "tempdynamics")
set_tests_properties(testTempDynamics PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;787;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testTempNLDynamics "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "tempnldynamics")
set_tests_properties(testTempNLDynamics PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;788;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest1 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm1")
set_tests_properties(testRtest1 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;789;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest2 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm2")
set_tests_properties(testRtest2 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;790;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest11 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm11")
set_tests_properties(testRtest11 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;791;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest13 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm13")
set_tests_properties(testRtest13 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;792;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest19 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm19")
set_tests_properties(testRtest19 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;794;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest20 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm20")
set_tests_properties(testRtest20 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;795;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest21 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm21")
set_tests_properties(testRtest21 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;796;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest22 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm22")
set_tests_properties(testRtest22 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;797;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest23 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm23")
set_tests_properties(testRtest23 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;798;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest24 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm24")
set_tests_properties(testRtest24 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;799;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest25 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm25")
set_tests_properties(testRtest25 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;800;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest27a "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm27a")
set_tests_properties(testRtest27a PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;801;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest27b "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm27b")
set_tests_properties(testRtest27b PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;802;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest29 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm29")
set_tests_properties(testRtest29 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;803;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest30 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm30")
set_tests_properties(testRtest30 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;804;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest31 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm31")
set_tests_properties(testRtest31 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;805;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest32 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm32")
set_tests_properties(testRtest32 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;806;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest35a "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm35a")
set_tests_properties(testRtest35a PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;810;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest35b "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm35b")
set_tests_properties(testRtest35b PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;811;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest37 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm37")
set_tests_properties(testRtest37 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;812;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest39 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm39")
set_tests_properties(testRtest39 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;814;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testRtest40 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "dsvm40")
set_tests_properties(testRtest40 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;815;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testvme1 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "vme1")
set_tests_properties(testvme1 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;816;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testvme3 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "vme3")
set_tests_properties(testvme3 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;818;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testvme4 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "vme4")
set_tests_properties(testvme4 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;819;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testvme5 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "vme5")
set_tests_properties(testvme5 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;820;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testvme6 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "vme6")
set_tests_properties(testvme6 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;821;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testvmmech003 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "vmmech003")
set_tests_properties(testvmmech003 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;822;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testvmmech063 "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "vmmech063")
set_tests_properties(testvmmech063 PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;823;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testPreStress "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "PreStressedMembrane")
set_tests_properties(testPreStress PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;824;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
add_test(testPressure "/home/anarkhede/tinkercliffs/FEMWorkingFoam/Regression.d/dataComp.py" "-l" "PlateUnderPressure")
set_tests_properties(testPressure PROPERTIES  _BACKTRACE_TRIPLES "/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;826;ADD_TEST;/home/anarkhede/tinkercliffs/FEMWorkingFoam/CMakeLists.txt;0;")
subdirs("Element.d")
subdirs("Feti.d")
subdirs("Driver.d")
subdirs("Comm.d")
subdirs("Corotational.d")
subdirs("Dec.d")
subdirs("Solvers.d")
subdirs("Utils.d")
subdirs("Parser.d")
subdirs("Timers.d")
subdirs("Threads.d")
subdirs("Mortar.d")
subdirs("Math.d")
subdirs("Linpack.d")
subdirs("Sfem.d")
subdirs("Paral.d")
subdirs("Problems.d")
subdirs("GNU-getopt.d")
subdirs("Hetero.d")
subdirs("Material.d")
subdirs("Rom.d")
subdirs("Regression.d")
subdirs("FetiLib")
subdirs("Acme.d")
