#define		A_cols	0
#define		A_nz	1
#define		L_cols	2
#define		L_nz	3
#define		i_m	4
#define		i_o	5
#define		i_r	6
#define		i_t	7
#define		s_m	8 
#define		s_o	9 
#define		s_r	10 
#define		s_t	12 
#define		s_d_m	13 
#define		s_d_o	14 
#define		s_d_r	15 
#define		s_d_t	16 
#define		s_l_m	17 
#define		s_l_o	18
#define		s_l_r	19 
#define		s_l_t	20
#define		n_m	21
#define		n_o	22
#define		n_r	23
#define		n_t	24
#define		n_d_m	25
#define		n_d_o	26
#define		n_d_r	27
#define		n_d_t	28
#define		n_l_m	29
#define		n_l_o	30
#define		n_l_r	31
#define		n_l_t	32
#define		so_m	33
#define		so_o	34
#define		so_r	35
#define		so_t	36
#define		so_d_m	37
#define		so_d_o	38
#define		so_d_r	39
#define		so_d_t	40
#define		so_l_m	41
#define		so_l_o	42
#define		so_l_r	43
#define		so_l_t	44
#define		all_i_t 45
#define		all_s_t 46
#define		all_n_t 47
#define		all_so_t 48
#define		A_mem		 50
#define		L_mem 		 51
#define		L_stack_peak 	 52
#define		order_extra_mem	 53
#define		s_factor_extra_mem 54
#define		n_factor_extra_mem 55
#define		fixed_mem 	 56
#define		L_stack 	 57
#define		mem_peak  	 58
#define		est_mem_peak  	 59
#define		est_total_mem 	 60
#define		obs_mem_peak  	 61
#define		obs_total_mem 	 62
#define		max_vec_error	 63
#define		max_count_error	 64
#define		sample_component 65
#define		solve_mem 	 66
#define		MAX_STATS	 70
#define		Million		1000000
#define		Thousand	1000
